# This file was generated by GoReleaser. DO NOT EDIT.
cask "aispace" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "ee320086bdbcbdec9cbf39a5980af9d1baa0c297fc8b3b0ae644e201ee195a00"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07235948f6cb6d015f28dc9ace69ba84c2cec51673d5bce25df24b5f3fa78274"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "19efd0bedfc5344fb191161eb037db319f5ba138aae2732e6c53b07679f295d4"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af3ff9e476067d9d81bccf176c5b8728d2b755223b4ed272732f81fa87f5dfb5"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_linux_amd64.tar.gz"
    end
  end

  name "aispace"
  desc "Secure temporary file sharing for AI agents and humans"
  homepage "https://aispace.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aispace"

  # No zap stanza required
end
