# This file was generated by GoReleaser. DO NOT EDIT.
cask "aispace" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "3797d946771562f0ec7d17b95fd33fe5e6ff64d809d48655874b0be7eaa239a1"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "65c096187ef59cfcda126f37a6ac838469c274f28092a4b0cb3f412c71924438"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9ca818c4ff5b9388dda373c0ad7dc01ca0687e700c09f556db7255c6c96b3634"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c5fa20a1ec3ccdf8ecde59ac2ee7e97ba0b06aedf944234450d90fd0ec97fd7"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_linux_amd64.tar.gz"
    end
  end

  name "aispace"
  desc "Bot-friendly file drop with expiring links"
  homepage "https://aispace.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aispace"

  # No zap stanza required
end
