# This file was generated by GoReleaser. DO NOT EDIT.
cask "aispace" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "e4afbd07204ea560da99d6296533ae4438b90140a4e602b45b2c509092afc877"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba9ef408f3132485e9b4aadf6bac5ac977eda4f3abeae4381695b85aa7a92e84"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a8a0ca1f8435e818150923f6b065b34ef80af0e41ff02f011e712c6c6625438"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd10a5956f635e112b0fa6c792c0960d68755292661e39b5b171648c46d28685"
      url "https://github.com/aispace-sh/aispace-client/releases/download/v#{version}/aispace_linux_amd64.tar.gz"
    end
  end

  name "aispace"
  desc "Secure temporary file sharing for AI agents and humans"
  homepage "https://aispace.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aispace"

  # No zap stanza required
end
